paths:
  source_folder: 'Assets/'
  json_source_file: 'data.json'
  json_destination_file: 'data_mod2.json'
  yaml_destination_file: 'data_ymod2.yaml'
  xml_source_file: 'data.xml'
  xml_destination_file: 'data_xmod2.xml'

jobs:
  - name: "deserialize"
    format: "xml"
  - name: "somestats"
  - name: "serialize"
    format: "yaml"
    source: "file"
  - name: "serialize"
    format: "xml"
    source: "object"
