# Etap 1 - użycie obrazu scratch
FROM scratch AS base
ADD alpine-minirootfs-3.21.3-x86_64.tar /

ARG VERSION=0.29
ENV APP_VERSION=$VERSION
ENV PROLOG_PORT=8080

# RUN apk add swi-prolog --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/

WORKDIR /usr/app
COPY server.pl ./server.pl

# Etap 2 - postawienie serwera NGINX
FROM nginx:latest

ARG VERSION=0.29
ENV APP_VERSION=$VERSION
ENV PROLOG_PORT=8080

RUN apt update && apt install -y swi-prolog

WORKDIR /usr/share/nginx/html

COPY --from=base /usr/app/server.pl ./server.pl
COPY nginx.conf /etc/nginx/nginx.conf

HEALTHCHECK --interval=60s --timeout=1s \
    CMD curl -f http://127.0.0.1 || exit 1

EXPOSE 80

CMD [ "sh", "-c", "nginx & swipl -s ./server.pl" ]
